### ISSUE TITLE
Explicit type declaration on arrays fails

### ISSUE THREAD

**Issue by falkecarlsen** [d409f19/cellmata#105]
`let arr = int {1, 2, 3, 4, 5}` fails with:

`mismatched input 'int' expecting {'#', DIGITS, FLOAT, '[', '(', '!', '-', 'true', 'false', IDENT}`

**Comment by NicEastvillage** [comment]
That is not valid syntax. It should be `[] int {1, 2, 3, 4, 5}` or just `{1, 2, 3, 4, 5}`
