### ISSUE TITLE
Missing features in examples

### ISSUE THREAD

**Issue by NicEastvillage** [d409f19/cellmata#25]
* for-loops
* continue-statement
* break-statement
* neighbourhood lookup, e.g. `moore[0] == Alive`
* Most expressions
* Multi state declaration
* Multi state index, `#`
* `elif`
* Array literal, e.g. `{1, 2, 3, 4}`

**Comment by jenrik** [comment]
`stress.cell` have the following features from the list:

- Multi state index, `#`
- `elif`
