### ISSUE TITLE
Power operator

### ISSUE THREAD

**Issue by falkecarlsen** [d409f19/cellmata#29]
We should probably add exponentiation. This operator should have a higher precedence than mult/div/mod, but lower than unary operators, scope, and array access, which puts it immediately after modulo.
`    | expr OP_POWER expr #powerExpr`

Where token is:
`OP_POWER : '**' ;`

**Comment by NicEastvillage** [comment]
Alternatively we just have a function called `pow(x)` which is what is currently in the report.

**Comment by falkecarlsen** [comment]
A cool side-effect of only having a built-in function is that we mirror C-like languages with operators :+1:
