### ISSUE TITLE
Add builtin function to symbol table

### ISSUE THREAD

**Issue by jenrik** [d409f19/cellmata#49]
The builtin functions should be added to the symbol table. Currently the builtin functions are part of a list of reserved words that are blocked from being inserted into the symbol table.

**Comment by jenrik** [comment]
#67 removes builtin functions from the reserved keyword list, but the builtin still needs to be created and added to the symbol table

**Comment by jenrik** [comment]
Closing this issue because creating the builtin functions are a separate task

**Comment by falkecarlsen** [comment]
Opening, as the symbol table still needs to be pre-filled with builtin function signatures.
