### ISSUE TITLE
Add commandline arguments

### ISSUE THREAD

**Issue by jenrik** [d409f19/cellmata#86]
We should add commandline arguments to configure the compiler. For instance we should have a debug information flag that save the AST after each phase using the graph printer from #63

**Comment by NicEastvillage** [comment]
Could you please add one issue per option requested.

**Comment by jenrik** [comment]
Sure, but I will keep this open both as a reminder to do so, and to be a meta issue for the entire need for commandline arguments

**Comment by jenrik** [comment]
Implemented in #151
